--event details table

CREATE TABLE EVENT_DETAILS (
SNO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
STUDENT_ID VARCHAR(10) NOT NULL REFERENCES STUDENTS_DETAILS(STUDENT_ID) ON DELETE CASCADE ,
GROUP_ID VARCHAR(10),
EVENT_ID VARCHAR(15),
COLLEGE_ID VARCHAR(10) NOT NULL REFERENCES COLLEGE_DETAILS(COLLEGE_ID) ON DELETE CASCADE,  
PRIMARY KEY(STUDENT_ID,EVENT_ID),
FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE 
);