--seminar table not include yet

--CREATE TABLE SEMINAR_DETAILS(
--SNO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
--NAME VARCHAR(100) NOT NULL, 
--COURSE VARCHAR(100) ,
--COLLEGE_NAME VARCHAR(150),
--ADDRESS VARCHAR(500),
--PHONE VARCHAR(12),
--EMAIL VARCHAR(100),
--DUTY_CERTIFICATE BOOLEAN NOT NULL DEFAULT FALSE
--);

