--student deatils table

CREATE TABLE STUDENTS_DETAILS(
SNO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
COLLEGE_ID VARCHAR(10) NOT NULL, 
STUDENT_ID VARCHAR(10) NOT NULL,
STUDENT_NAME VARCHAR(150),
STUDENT_GENDER CHAR(1),
STUDENT_PHONE VARCHAR(12),
STUDENT_POINT FLOAT NOT NULL DEFAULT 0.0,
STATUS BOOLEAN NOT NULL DEFAULT TRUE,
ACCOMMODATION BOOLEAN  DEFAULT FALSE,
PRIMARY KEY(STUDENT_ID),
FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE_DETAILS(COLLEGE_ID) ON DELETE CASCADE  
);
