-- time sheet table

CREATE TABLE TIMESHEET(
SNO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
EVENT_ID VARCHAR(15),
START_TIME VARCHAR(20),
END_TIME VARCHAR(20),
EVENT_STAGE VARCHAR(20),
VENUE  VARCHAR(200) ,
DAY DATE
);
