--winner table 
CREATE TABLE WINNERS(
SNO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
COLLEGE_ID VARCHAR(10) NOT NULL ,
STUDENT_ID VARCHAR(10) NOT NULL REFERENCES STUDENTS_DETAILS(STUDENT_ID) ON DELETE CASCADE ,
EVENT_ID VARCHAR(15) NOT NULL REFERENCES EVENTS(EVENT_ID)ON DELETE CASCADE ,
WINNER_STATUS VARCHAR(15) NOT NULL,
GROUP_ID VARCHAR(10),
MARK FLOAT NOT NULL DEFAULT -999999,
PRIMARY KEY(GROUP_ID,EVENT_ID,STUDENT_ID),
FOREIGN KEY(COLLEGE_ID) REFERENCES COLLEGE_DETAILS(COLLEGE_ID) ON DELETE CASCADE 	
);